"""empty message

Revision ID: 137182761d88
Revises: 78a33c4125e5
Create Date: 2018-01-05 20:00:35.193440

"""

# revision identifiers, used by Alembic.
revision = '137182761d88'
down_revision = '78a33c4125e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
