"""empty message

Revision ID: 259778b5d5e2
Revises: 79e196826e73
Create Date: 2018-01-07 16:01:39.333970

"""

# revision identifiers, used by Alembic.
revision = '259778b5d5e2'
down_revision = '79e196826e73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
