"""empty message

Revision ID: 4ce5ac4a16e8
Revises: eaa7560dd822
Create Date: 2018-01-05 22:52:59.529850

"""

# revision identifiers, used by Alembic.
revision = '4ce5ac4a16e8'
down_revision = 'eaa7560dd822'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'name')
    # ### end Alembic commands ###
