"""empty message

Revision ID: 78a33c4125e5
Revises: None
Create Date: 2018-01-05 12:28:22.004208

"""

# revision identifiers, used by Alembic.
revision = '78a33c4125e5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
