"""empty message

Revision ID: 79e196826e73
Revises: b540e1309cb3
Create Date: 2018-01-07 16:01:33.904705

"""

# revision identifiers, used by Alembic.
revision = '79e196826e73'
down_revision = 'b540e1309cb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('slug', sa.Text(), nullable=True))
    op.create_index(op.f('ix_game_slug'), 'game', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_slug'), table_name='game')
    op.drop_column('game', 'slug')
    # ### end Alembic commands ###
