"""empty message

Revision ID: b540e1309cb3
Revises: f9c24abe576a
Create Date: 2018-01-06 11:39:21.794879

"""

# revision identifiers, used by Alembic.
revision = 'b540e1309cb3'
down_revision = 'f9c24abe576a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
