"""empty message

Revision ID: dbfc6b044099
Revises: 4ce5ac4a16e8
Create Date: 2018-01-06 11:37:40.728586

"""

# revision identifiers, used by Alembic.
revision = 'dbfc6b044099'
down_revision = '4ce5ac4a16e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('competition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'competition', 'competition', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competition', type_='foreignkey')
    op.drop_column('competition', 'competition_id')
    # ### end Alembic commands ###
