"""empty message

Revision ID: eaa7560dd822
Revises: 137182761d88
Create Date: 2018-01-05 20:07:48.880758

"""

# revision identifiers, used by Alembic.
revision = 'eaa7560dd822'
down_revision = '137182761d88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
