"""empty message

Revision ID: f9c24abe576a
Revises: dbfc6b044099
Create Date: 2018-01-06 11:38:45.893305

"""

# revision identifiers, used by Alembic.
revision = 'f9c24abe576a'
down_revision = 'dbfc6b044099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('game_id', sa.Integer(), nullable=False))
    op.drop_constraint('competition_competition_id_fkey', 'competition', type_='foreignkey')
    op.create_foreign_key(None, 'competition', 'game', ['game_id'], ['id'])
    op.drop_column('competition', 'competition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('competition_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'competition', type_='foreignkey')
    op.create_foreign_key('competition_competition_id_fkey', 'competition', 'competition', ['competition_id'], ['id'])
    op.drop_column('competition', 'game_id')
    # ### end Alembic commands ###
