site_name: Pommerman
theme: material
markdown_extensions:
  - codehilite
repo_url: http://github.com/MultiAgentLearning/playground
site_url: http://pommerman.com/
site_description: 'Documentation for Pommerman.'

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Command Line Interface: CLI.md
  - Multiplayer: multiplayer.md
  - Competitions: competitions.md
  - Environment Reference: environment.md
  - Research Topics: research.md